### ISSUE TITLE
6a grabless doesn't tick off

### ISSUE THREAD

**Issue by Retrisma** [rhelmot/CelesteBingoClient#19] opened 2021-02-24 16:13 UTC
the progress graph seems to recognize 5/6 subchapters completed grabless

update: the subchapter it doesn't recognize as completed grabless is Resolution

**Comment by rhelmot** [comment] 2021-02-25 01:17
I wasn't able to reproduce this, actually. Can you try out some of these commands in the c# console and see if any of them return anything different when you're in the state where you've actually completed it but it isn't registered?

![image](https://user-images.githubusercontent.com/2498805/109088280-61bb4180-76cc-11eb-8ff4-f1f217451ef6.png)

For this, I force-enabled grabless mode as if I had had it on since the start of the chapter at the start of the resolution checkpoint, so for you there will be more items in the VariantCompletions list, one for each checkpoint you've done grabless.

**Comment by rhelmot** [comment] 2021-02-25 01:18
oh also 
![image](https://user-images.githubusercontent.com/2498805/109088453-a5ae4680-76cc-11eb-99ea-760905d108c8.png)

**Comment by Retrisma** [comment] 2021-02-25 02:40
Unfortunately I don't have access to the c# prompt, unsure why. Paying closer attention playing through 6a and watching the progress bar advance, though, I noticed that it was actually 6a Start that wasn't being recognized, not Reso. I'm really sorry about that

**Comment by rhelmot** [comment] 2021-02-25 02:41
The c# prompt is a mod! https://gamebanana.com/tools/6971

**Comment by Retrisma** [comment] 2021-02-25 02:42
Oh cool! Thanks for the link, will install now. I'm also messing around more in Start to see if I can get it to advance (turning on Grabless in the opening cutscene, etc.)

**Comment by rhelmot** [comment] 2021-02-25 02:44
Oh, yeah, you definitely need to turn on grabless for the starjump cutscene. You'll have to turn it on using the spawnpoint at the far left side of the screen, at least until I release the next update.

**Comment by Retrisma** [comment] 2021-02-25 02:46
Yeah, that's what I did the very first time, but I'm experimenting with the *opening* opening cutscene. I looked through your code and I couldn't tell what wouldn't be working, so I'm kinda just messing around. But yeah, I put it on before you could control madeline, whereas when I first opened this issue I put it on before I entered the first feather

**Comment by Retrisma** [comment] 2021-02-25 02:52
Aha! When I didn't skip the final cutscene of Start with Badeline, it counted as completing Start grabless. Maybe something to do with Madeline falling?

**Comment by rhelmot** [comment] 2021-02-25 03:17
I got it! It's because rooms were only tracked on screen transitions, and the warp does not count as one. It should be fixed next release.

**Closed as completed by rhelmot** 2021-02-25 03:17 UTC
